version: '3.3'

services:
  web:
    build: .
    container_name: fitlife-frontend-server
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
